# Generated by Django 4.1.5 on 2023-01-05 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='date_Achat',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
